services:

    #Front End
    temperature-fe:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: temperature-fe
        container_name: temperature-fe
        restart: unless-stopped
        ports:
            - "81:80"
    
    #Back End
    temperature-be:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: temperature-be
        container_name: temperature-be
        restart: unless-stopped
        ports:
            - "3001:3000"

    #Mongo DB Service
    mongodb:
      image: mongo:latest
      container_name: temperature-mongodb
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootPassword
      volumes:
        - ./data/mongodb:/data/db