services:

    #Front End
    temperature-fe:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: temperature-fe
        container_name: temperature-fe
        restart: unless-stopped
        ports:
            - "80:80"
    
    #Back End
    temperature-be:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: temperature-be
        container_name: temperature-be
        restart: unless-stopped
        ports:
            - "3000:3000"
            - "4000:4000"

    #Mongo DB Service
    mongodb:
      image: mongo:latest
      container_name: temperature-mongodb
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootPassword
      volumes:
        - ./volume/mongodb/mongod.conf:/etc/mongod.conf
        - ./data/mongodb:/data/db
      command: ["mongod", "--config", "/etc/mongod.conf"]

networks:
  mynetwork:
    driver: bridge