services:

    #Front End
    temperature-fe:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: temperature-fe
        container_name: temperature-fe
        restart: unless-stopped
        ports:
            - "81:80"
    
    #Back End
    temperature-be:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: temperature-be
        container_name: temperature-be
        restart: unless-stopped
        ports:
            - "3001:3000"